---
#-------------------------------
# General Site Settings

title: Runon
logo:
author: macle
description: Quant(퀀트), 로보어드바이저
email: ysys86a@email.com
phone: contact 참조
address: contact 참조
copyright:

menu:
  - { name: About, link: "/about" }
  - { name: Blog, link: "https://runonio.blogspot.com/" }
#  - { name: Git, link: "https://github.com/runonio" }
#  - { name: AI, link: "http://moara.ai" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: runon-1 # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Quant Lab. survive in the market

#social:
#  - { icon: "ti-facebook", link: "#" }
#  - { icon: "ti-instagram", link: "#" }
#  - { icon: "ti-dribbble", link: "#" }
#  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb:  기업분석, 금융데이터 확보, 데이터 분석, 퀀트를 연구하고 있습니다. <br> 전략적인 부분을 제외하고는 오픈소스로 프로젝트를 진행하고 있습니다.

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Work Process Section
#work-process:
#  - title: "투자 계획"
#    icon: "assets/images/icons/plan.png"
#    content: "분석 플랫폼을 활용하여 현 시점에 유리한 투자를 계획합니다."
#
#  - title: "백테스팅"
#    icon: "assets/images/icons/plan.png"
#    content: "투자계획을 검증 합니다."
#
#  - title: "운영 반영"
#    icon: "assets/images/icons/plan.png"
#    content: "검증된 투자계획을 바탕으로 봇이 자산을 관리 합니다."

# My Team Section
#team:
#  - title: "Jack Schenziwe"
#    image: "assets/images/team/member-1.png"
#    designation: "Project Manager"
#
#  - title: "Julias Carlie"
#    image: "assets/images/team/member-2.png"
#    designation: "Web Developer"
#
#  - title: "John Doe"
#    image: "assets/images/team/member-3.png"
#    designation: "Designer"

#-------------------------------
# Skills Section

#skills-title: Skills
#skills:
#  - { name: Web Design, color: "#fdb157", value: "90%" }
#  - { name: Logo Design, color: "#9473e6", value: "60%" }
#  - { name: After Effects, color: "#bdecf6", value: "80%" }
#  - { name: Web App, color: "#ffbcaa", value: "70%" }

#-------------------------------
# Exprerience Section

#experience-title: Experience
#experience:
#  - {
#      name: Junior UX Designer,
#      icon: "icon-1.png",
#      date: "Jan 2007 - Feb 2009",
#      organization: "WEBEX",
#    }
#  - {
#      name: UX & UI Designer,
#      icon: "icon-2.png",
#      date: "Mar 2009 - Aug 2014",
#      organization: "AUGMEDIX",
#    }
#  - {
#      name: Senior UI Designer,
#      icon: "icon-3.png",
#      date: "Sep 2014 - Present",
#      organization: "THEMEFISHER",
#    }

#-------------------------------
# Education Section

#education-title: Education
#education:
#  - {
#      name: Marters in UX Design,
#      date: "2006",
#      organization: "Masassusets Institute of Technology",
#    }
#  - {
#      name: Honours in Fine Arts,
#      date: "2004",
#      organization: "Harvard University",
#    }
#  - {
#      name: Higher Secondary Certificat,
#      date: "2000",
#      organization: "Cardiff School",
#    }
#  - {
#      name: Secondary School Certificate,
#      date: "1998",
#      organization: "Cardiff School",
#    }

#-------------------------------
# Services Section

services-title: What is being done in runon
services:
  - {
    name: 오픈소스,
    icon: ti-panel,
    description: "",
    active: true, # Add true to select section
    url: "https://github.com/runonio",
  }
#  - {
#      name: 연구-개발 방향성,
#      icon: ti-wand,
#      description: "",
#      active: false, # Add true to select section
#      moveurl: "https://runon.io/2024/09/10/quant_direction/",
#    }
#  - {
#    name: Quant Lab,
#    icon: ti-stats-up,
#    description: "",
#    active: true, # Add true to select section
#    moveurl: "/about",
#  }

  - {
    name: Blog,
    icon: ti-comment,
    description: "",
    active: false, # Add true to select section
    url: "https://runonio.blogspot.com/",
  }
  - {
    name: AI,
    icon: ti-user,
    description: "",
    active: true, # Add true to select section
    url: "http://moara.ai",
  }
#  - {
#    name: Financial Data,
#    icon: ti-files,
#    description: "",
#    active: false, # Add true to select section
#    #    moveurl: "/about",
#  }


#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
#portfolio-home-items:
#  - image: "assets/images/portfolio/item-1.png"
#    url: "#"
#
#  - image: "assets/images/portfolio/item-2.png"
#    url: "#"
#
#  - image: "assets/images/portfolio/item-3.png"
#    url: "#"
#
#  - image: "assets/images/portfolio/item-4.png"
#    url: "#"
#
#  - image: "assets/images/portfolio/item-5.png"
#    url: "#"
#
## Portfolio Page
#portfolio-label:
#  - { title: "UI/UX Design", type: "design" }
#  - { title: "BRANDING", type: "branding" }
#  - { title: "ILLUSTRATION", type: "illustration" }
#
#portfolio-items:
#  - image: "assets/images/portfolio/item-1.png"
#    url: "#"
#    portfolio-type:
#      - type: "design"
#      - type: "illustration"
#
#  - image: "assets/images/portfolio/item-2.png"
#    url: "#"
#    portfolio-type:
#      - type: "branding"
#
#  - image: "assets/images/portfolio/item-3.png"
#    url: "#"
#    portfolio-type:
#      - type: "illustration"
#
#  - image: "assets/images/portfolio/item-6.png"
#    url: "#"
#    portfolio-type:
#      - type: "design"
#      - type: "branding"
#
#  - image: "assets/images/portfolio/item-8.png"
#    url: "#"
#    portfolio-type:
#      - type: "illustration"
#
#  - image: "assets/images/portfolio/item-5.png"
#    url: "#"
#    portfolio-type:
#      - type: "design"
#
#  - image: "assets/images/portfolio/item-1.png"
#    url: "#"
#    portfolio-type:
#      - type: "branding"
#
#  - image: "assets/images/portfolio/item-3.png"
#    url: "#"
#    portfolio-type:
#      - type: "design"
#      - type: "illustration"
#      - type: "branding"
#
#  - image: "assets/images/portfolio/item-7.png"
#    url: "#"
#    portfolio-type:
#      - type: "illustration"

#-------------------------------
# Testimonials Section

#
#testimonial-items:
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
#
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
#
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
#
##-------------------------------
## Client Slider Section
#
#client-slider-items:
#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "https:moara.ai"
#
#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "https:moara.ai"
#
#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "https:moara.ai"
#
#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "https:moara.ai"
#
#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "https:moara.ai"
#
#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "https:moara.ai"
#
#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "https:moara.ai"
#
#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "https:moara.ai"
#
#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "https:moara.ai"
#
#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "https:moara.ai"

#-------------------------------
# Contact Section

contact-title: contact
contact-email: ysys86a@gmail.com
